### ISSUE TITLE
Problem of operations priority 

### ISSUE THREAD

**Issue by Tonioverzeworld** [jullianm/projet7OC#1]
![capture d ecran 2018-06-05 a 13 40 54](https://user-images.githubusercontent.com/3941062/40996006-610364f0-68c6-11e8-84f8-e186d76b7f2b.png)

we must have 17 as a result here

**Comment by jullianm** [comment]
Issue resolved, user can now use * and / along with operators + and - in a calculation, it will be prioritized and total will be correct.
