### ISSUE TITLE
Improvement: use tag button for more efficiency on tappedNumberButton function

### ISSUE THREAD

**Issue by Tonioverzeworld** [jullianm/projet7OC#3]
You can improve the tappedNumberButton function 
![capture d ecran 2018-06-05 a 13 51 18](https://user-images.githubusercontent.com/3941062/40996521-9de01e08-68c7-11e8-8e05-762359359eef.png)
using the tag property of the buttons
![capture d ecran 2018-06-05 a 13 53 06](https://user-images.githubusercontent.com/3941062/40996636-ecceaade-68c7-11e8-9674-2690c7524306.png)

**Comment by jullianm** [comment]
Issue resolved using tags
